spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentalbikedb
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1000KB
      max-request-size: 1000KB
logging:
  level:
    org:
      hibernate:
        type: trace
server:
  servlet:
    contextPath: /rentalbike